EmaxCuadrillas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^principal/', include('principal.urls'), name='principal'),
    url(r'^casos/', include('casos.urls', namespace='casos')),
    url(r'^cuadrillas/', include('cuadrillas.urls', namespace='cuadrillas')),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^accounts/login/', login, {'template_name':'usuario/index.html'}, name='login'),
    url(r'^logout/', logout_then_login,  name='logout'),
    url(r'^reset/password_reset', password_reset, {'template_name':'Registration/password_reset_form.html', 'email_template_name':'Registration/password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'Registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, {'template_name':'Registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name':'Registration/password_reset_complete.html'}, name='password_reset_complete'),
]

casos/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import CasoCreateView, CasoListView, TareaCreateView, TareaListView, TareaUpdateView, TareaDeleteView, CasoUpdateView, CasoDeleteView

# Estas son la urls de casos
urlpatterns = [
    url(r'^eliminartarea/(?P<pk>\d+)/', login_required(TareaDeleteView.as_view()), name='eliminar_tarea'),
    url(r'^editartarea/(?P<pk>\d+)/', login_required(TareaUpdateView.as_view()), name='editar_tarea'),
    url(r'^listatarea', login_required(TareaListView.as_view()), name='tarea_lista'),
    url(r'^tarea', login_required(TareaCreateView.as_view()), name='tarea_nueva'),

    url(r'^eliminarcaso/(?P<pk>\d+)/', login_required(CasoDeleteView.as_view()), name='eliminar_caso'),
    url(r'^editarcaso/(?P<pk>\d+)/', login_required(CasoUpdateView.as_view()), name='editar_caso'),
    url(r'^listacaso', login_required(CasoListView.as_view()), name='caso_lista'),
    url(r'^nuevo', login_required(CasoCreateView.as_view()), name='caso_nuevo')
]

cuadrillas/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import IntegranteCreateView, FamiliarDeleteView, FamiliarUpdateView, FamiliarCreateView, FamiliarListView, IntegranteUpdateView, IntegranteDeleteView, CuadrillaUpdateView, CuadrillaCreateView, CuadrillaListView, IntegranteListView, CuadrillaDeleteView

urlpatterns = [
    url(r'^eliminarfamiliar/(?P<pk>\d+)/', login_required(FamiliarDeleteView.as_view()), name='eliminar_familiar'),
    url(r'^editarfamiliar/(?P<pk>\d+)/', login_required(FamiliarUpdateView.as_view()), name='editar_familiar'),
    url(r'^listafamiliar', login_required(FamiliarListView.as_view()), name='lista_familiar'),
    url(r'^nuevofamiliar', login_required(FamiliarCreateView.as_view()), name='familiar_nuevo'),

    url(r'^eliminarintegrante/(?P<pk>\d+)/', login_required(IntegranteDeleteView.as_view()), name='eliminar_integrante'),
    url(r'^editarintegrante/(?P<pk>\d+)/', login_required(IntegranteUpdateView.as_view()), name='editar_integrante'),
    url(r'^listaintegrantes', login_required(IntegranteListView.as_view()), name='lista_integrantes'),
    url(r'^nuevointegrante', login_required(IntegranteCreateView.as_view()), name='integrante_nuevo'),

    url(r'^eliminarcuadrilla/(?P<pk>\d+)/', login_required(CuadrillaDeleteView.as_view()), name='eliminar_cuadrilla'),
    url(r'^editarcuadrilla/(?P<pk>\d+)/', login_required(CuadrillaUpdateView.as_view()), name='editar_cuadrilla'),
    url(r'^listacuadrilla', login_required(CuadrillaListView.as_view()), name='lista_cuadrilla'),
    url(r'^nuevacuadrilla', login_required(CuadrillaCreateView.as_view()), name='cuadrilla_nueva'),
    ]

cuadrillas/models.py
from django.db import models

#Modelo de Cuadrilla
class Cuadrilla(models.Model):
    id = models.AutoField(primary_key=True)
    #fecha automatica saca error
    #fecha_creacion = models.DateField(auto_now_add=True)
    fecha_creacion = models.DateField(null = True, blank= True)

    def __str__(self):
        return self.fecha_creacion


#Modelo de los integrantes
class Integrante(models.Model):
    #Tupla de los tipos de integrantes
    TIPOS_INTEGRANTES = (
        ('1', 'Albañil'),
        ('2', 'Maestro de obra')
    )

    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=80,null=False, blank=True)
    apellido = models.CharField(max_length=80, null=False, blank=True)
    fecha_nacimiento = models.DateField(null=False, blank=False)
    direccion = models.CharField(max_length=100, null=False, blank=True)
    tipo = models.CharField(
        max_length=1,
        choices=TIPOS_INTEGRANTES,
        default='1'
    )

    #Llave foranea de la cuadrilla
    cuadrilla = models.ForeignKey('Cuadrilla', null=False, blank = True)

    def __str__(self):
        return self.nombre

#Modelo de los Familiares
class Familiar(models.Model):
    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=80, null=False, blank=False)
    parentesco = models.CharField(max_length=45, null=False, blank=False)
    telefono = models.CharField(max_length=8, null=False, blank=False)
    #Llave foranea de los integrantes
    integrante = models.ForeignKey('Integrante', null=False, blank=False)

cuadrillas/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
    CreateView
)
from .models import Cuadrilla, Familiar, Integrante

#vista de la creación de un nuevo integrante
class IntegranteCreateView(CreateView):
    model = Integrante
    fields = [
    'nombre',
    'apellido',
    'fecha_nacimiento',
    'direccion',
    'tipo',
    'cuadrilla',
    ]
    template_name = 'cuadrillas/integrante_nuevo.html'
    success_url = reverse_lazy('cuadrillas:lista_integrantes')

class IntegranteListView(ListView):
    model = Integrante
    template_name = 'cuadrillas/integrantes_list.html'
    context_object_name = 'integrantes'
#vista de la creción de una nueva cuadrilla

class IntegranteUpdateView(UpdateView):
    model = Integrante
    fields = [
    'nombre',
    'apellido',
    'fecha_nacimiento',
    'direccion',
    'tipo',
    'cuadrilla',
    ]
    template_name = 'cuadrillas/integrante_nuevo.html'
    success_url = reverse_lazy('cuadrillas:lista_integrantes')

class IntegranteDeleteView(DeleteView):
    model = Integrante
    fields = [
    'nombre',
    'apellido',
    'fecha_nacimiento',
    'direccion',
    'tipo',
    'cuadrilla',
    ]
    template_name = 'cuadrillas/integrante_delete.html'
    success_url = reverse_lazy('cuadrillas:lista_integrantes')

class FamiliarCreateView(CreateView):
    model = Familiar
    fields = [
        'nombre',
        'parentesco',
        'telefono',
        'integrante'
    ]
    template_name = 'cuadrillas/familiar_nuevo.html'
    # succes_url es la dirección a la que se redirige
    # al ompletar la transacción sólo si es exitosa
    success_url = reverse_lazy('cuadrillas:lista_familiar')

    def __str__(self):
        return self.nombre

class FamiliarListView(ListView):
        model = Familiar
        template_name = 'cuadrillas/familiar_list.html'
        context_object_name = 'familiar'

class FamiliarUpdateView(UpdateView):
    model = Familiar
    fields = [
        'nombre',
        'parentesco',
        'telefono',
        'integrante'
    ]
    template_name = 'cuadrillas/familiar_nuevo.html'
    success_url = reverse_lazy('cuadrillas:lista_familiar')

class FamiliarDeleteView(DeleteView):
    model = Familiar
    fields = [
        'nombre',
        'parentesco',
        'telefono',
        'integrante'
    ]
    template_name = 'cuadrillas/familiar_delete.html'
    success_url = reverse_lazy('cuadrillas:lista_familiar')



#vista de la creación de una nueva cuadrilla
class CuadrillaCreateView(CreateView):
    model = Cuadrilla
    fields = [
        'fecha_creacion',
    ]
    template_name = 'cuadrillas/cuadrilla_nuevo.html'
    # succes_url es la dirección a la que se redirige
    # al ompletar la transacción sólo si es exitosa
    success_url = reverse_lazy('cuadrillas:lista_cuadrilla')

    def __str__(self):
        return self.fecha_creacion

#vista de la lista de cuadrillas
class CuadrillaListView(ListView):
    model = Cuadrilla
    template_name = 'cuadrillas/cuadrillas_list.html'
    context_object_name = 'cuadrillas'

class CuadrillaUpdateView(UpdateView):
    model = Cuadrilla
    fields = [
        'fecha_creacion',
    ]
    template_name = 'cuadrillas/cuadrilla_nuevo.html'
    success_url = reverse_lazy('cuadrillas:lista_cuadrilla')

class CuadrillaDeleteView(DeleteView):
    model = Cuadrilla
    fields = [
        'fecha_creacion',
    ]
    template_name = 'cuadrillas/cuadrilla_delete.html'
    success_url = reverse_lazy('cuadrillas:lista_cuadrilla')

templates/cuadrillas/cuadrilla_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content %}
    <form method="post">
      {% csrf_token %}
      <h3>¿Desea eliminar el registro de {{ object.fecha_nacimiento }}?</h3>
      <button class="btn btn-danger" type="submit">Sí, Eliminar</button>
      <a class= "btn btn-default" href="{% url 'cuadrillas:lista_cuadrilla' %}">Cancelar</a>
    </form>
    {% endblock %}

  </body>
</html>

templates/cuadrillas/cuadrilla_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>cuadrilla</title>
  </head>
  <body>
    {% block content %}
      {% csrf_token %}
      {% for cuadrillas in cuadrillas %}
          <tr>
            <li>
            <td>{{cuadrillas.fecha_creacion}}</td>
            <td>
              <a class "btn btn-primary" href="{% url 'cuadrillas:editar_cuadrilla' cuadrillas.id %}">Editar</a>
              <a class "btn btn-primary" href="{% url 'cuadrillas:eliminar_cuadrilla' cuadrillas.id %}">Eliminar</a>
            </td>
            </li>
          </tr>
      {% endfor %}
    {% endblock %}
  </body>
</html>

templates/cuadrillas/cuadrilla_nuevo.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit"> Guardar</button>
    </form>
  </body>
</html>

templates/cuadrillas/familiar_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content %}
    <form method="post">
      {% csrf_token %}
      <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
      <button class="btn btn-danger" type="submit">Sí, Eliminar</button>
      <a class= "btn btn-default" href="{% url 'cuadrillas:lista_familiar' %}">Cancelar</a>
    </form>
    {% endblock %}

  </body>
</html>

templates/cuadrillas/familiar_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>familiares</title>
  </head>
  <body>
    {% block content %}
      {% csrf_token %}
      {% for familiar in familiar %}
          <tr>
            <li>
            <td>{{familiar.nombre}}</td>
            <td>{{familiar.parentesco}}</td>
            <td>{{familiar.telefono}}</td>
            <td>{{familiar.integrante}}</td>
            <a class "btn btn-primary" href="{% url 'cuadrillas:editar_familiar' familiar.id %}">Editar</a>
            <a class "btn btn-primary" href="{% url 'cuadrillas:eliminar_familiar' familiar.id %}">Eliminar</a>
            </li>
          </tr>
      {% endfor %}
    {% endblock %}
  </body>
</html>

templates/cuadrillas/familiar_nuevo.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="" method="post">
      {% csrf_token %}
      {{form.as_p}}
      <button type="submit"> Guardar</button>
    </form>
  </body>
</html>

templates/cuadrillas/integrante_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content %}
    <form method="post">
      {% csrf_token %}
      <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
      <button class="btn btn-danger" type="submit">Sí, Eliminar</button>
      <a class= "btn btn-default" href="{% url 'cuadrillas:lista_integrantes' %}">Cancelar</a>
    </form>
    {% endblock %}

  </body>
</html>

templates/cuadrillas/integrante_list.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>integrante</title>
  </head>
  <body>
    {% block content %}
      {% csrf_token %}
      {% for integrantes in integrantes %}
          <tr>
            <li>
            <td>{{integrantes.nombre}}</td>
            <td>{{integrantes.apellido}}</td>
            <td>{{integrantes.fecha_nacimiento}}</td>
            <td>{{integrantes.direccion}}</td>
            <a class "btn btn-primary" href="{% url 'cuadrillas:editar_integrante' integrantes.id %}">Editar</a>
            <a class "btn btn-primary" href="{% url 'cuadrillas:eliminar_integrante' integrantes.id %}">Eliminar</a>
            </li>
          </tr>
      {% endfor %}
    {% endblock %}
  </body>
</html>

templates/cuadrillas/integrante_nuevo.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <form class="" action="" method="post">
      {% csrf_token %}
      <h4>Nombre  {{form.nombre}}</h4>
      <h4>Apellido  {{form.apellido}}</h4>
      <h4>Fecha de Nacimiento  {{form.fecha_nacimiento}}</h4>
      <h4>Direccion  {{form.direccion}}</h4>
      <h4>Tipo  {{form.tipo}}</h4>
      <button type="submit"> Guardar</button>
    </form>
  </body>
</html>