EmaxCuadrillas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^principal/', include('principal.urls'), name='principal'),
    url(r'^casos/', include('casos.urls', namespace='casos')),
    url(r'^cuadrillas/', include('cuadrillas.urls', namespace='cuadrillas')),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^accounts/login/', login, {'template_name':'usuario/index.html'}, name='login'),
    url(r'^logout/', logout_then_login,  name='logout'),
    url(r'^reset/password_reset', password_reset, {'template_name':'Registration/password_reset_form.html', 'email_template_name':'Registration/password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'Registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, {'template_name':'Registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name':'Registration/password_reset_complete.html'}, name='password_reset_complete'),
]

casos/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import CasoCreateView, CasoListView, TareaCreateView, TareaListView, TareaUpdateView, TareaDeleteView, CasoUpdateView, CasoDeleteView

# Estas son la urls de casos
urlpatterns = [
    url(r'^eliminartarea/(?P<pk>\d+)/', login_required(TareaDeleteView.as_view()), name='eliminar_tarea'),
    url(r'^editartarea/(?P<pk>\d+)/', login_required(TareaUpdateView.as_view()), name='editar_tarea'),
    url(r'^listatarea', login_required(TareaListView.as_view()), name='tarea_lista'),
    url(r'^tarea', login_required(TareaCreateView.as_view()), name='tarea_nueva'),

    url(r'^eliminarcaso/(?P<pk>\d+)/', login_required(CasoDeleteView.as_view()), name='eliminar_caso'),
    url(r'^editarcaso/(?P<pk>\d+)/', login_required(CasoUpdateView.as_view()), name='editar_caso'),
    url(r'^listacaso', login_required(CasoListView.as_view()), name='caso_lista'),
    url(r'^nuevo', login_required(CasoCreateView.as_view()), name='caso_nuevo')
]

cuadrillas/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import IntegranteCreateView, FamiliarDeleteView, FamiliarUpdateView, FamiliarCreateView, FamiliarListView, IntegranteUpdateView, IntegranteDeleteView, CuadrillaUpdateView, CuadrillaCreateView, CuadrillaListView, IntegranteListView, CuadrillaDeleteView

urlpatterns = [
    url(r'^eliminarfamiliar/(?P<pk>\d+)/', login_required(FamiliarDeleteView.as_view()), name='eliminar_familiar'),
    url(r'^editarfamiliar/(?P<pk>\d+)/', login_required(FamiliarUpdateView.as_view()), name='editar_familiar'),
    url(r'^listafamiliar', login_required(FamiliarListView.as_view()), name='lista_familiar'),
    url(r'^nuevofamiliar', login_required(FamiliarCreateView.as_view()), name='familiar_nuevo'),

    url(r'^eliminarintegrante/(?P<pk>\d+)/', login_required(IntegranteDeleteView.as_view()), name='eliminar_integrante'),
    url(r'^editarintegrante/(?P<pk>\d+)/', login_required(IntegranteUpdateView.as_view()), name='editar_integrante'),
    url(r'^listaintegrantes', login_required(IntegranteListView.as_view()), name='lista_integrantes'),
    url(r'^nuevointegrante', login_required(IntegranteCreateView.as_view()), name='integrante_nuevo'),

    url(r'^eliminarcuadrilla/(?P<pk>\d+)/', login_required(CuadrillaDeleteView.as_view()), name='eliminar_cuadrilla'),
    url(r'^editarcuadrilla/(?P<pk>\d+)/', login_required(CuadrillaUpdateView.as_view()), name='editar_cuadrilla'),
    url(r'^listacuadrilla', login_required(CuadrillaListView.as_view()), name='lista_cuadrilla'),
    url(r'^nuevacuadrilla', login_required(CuadrillaCreateView.as_view()), name='cuadrilla_nueva'),
    ]

principal/urls.py
from django.conf.urls import url, include
from principal.views import index

urlpatterns = [
    url(r'^$', index),
]

usuario/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from usuario.views import RegistroUsuario

urlpatterns = [
    url(r'^registrar', login_required(RegistroUsuario.as_view()), name='registrar_usuario'),
 ]

principal/models.py
from django.db import models

# Create your models here.

principal/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required (login_url = '/accounts/login/')
def index(request):
    return render(request, 'principal/principal.html')

# Create your views here.

templates/principal/principal.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Principal{%endblock%}</title>
  </head>
  <body>
    {% block header %}
    <h4>Titulo</h4>
    {% endblock %}

    {% block content %}
    <form method="post">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="form-group">
            <h2>Casos</h2>
            <li><a href="{% url 'casos:caso_nuevo' %}">Nuevo Caso</a></li>
            <li><a href="{% url 'casos:caso_lista' %}">Lista Caso</a></li>
          </div>
        </div>
      </div>
    </form>
    <form method="post">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="form-group">
            <h2>Tareas</h2>
            <li><a href="{% url 'casos:tarea_nueva' %}">Nueva Tarea</a></li>
            <li><a href="{% url 'casos:tarea_lista' %}">Lista Tareas</a></li>
          </div>
        </div>
      </div>
    </form>
    <form method="post">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="form-group">
            <h2>Cuadrillas</h2>
            <li><a href="{% url 'cuadrillas:cuadrilla_nueva' %}">Nueva Cuadrilla</a></li>
            <li><a href="{% url 'cuadrillas:lista_cuadrilla' %}">Lista Cuadrilla</a></li>
          </div>
        </div>
      </div>
    </form>
    <form method="post">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="form-group">
            <h2>Personal</h2>
            <li><a href="{% url 'cuadrillas:integrante_nuevo' %}">Nuevo Integrante</a></li>
            <li><a href="{% url 'cuadrillas:lista_integrantes' %}">Lista de Integrantes</a></li>
          </div>
        </div>
      </div>
    </form>
    <form method="post">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="form-group">
            <h2>Familiares</h2>
            <li><a href="{% url 'cuadrillas:familiar_nuevo' %}">Nuevo Familiar</a></li>
            <li><a href="{% url 'cuadrillas:lista_familiar' %}">Lista de Familiares</a></li>
          </div>
        </div>
      </div>
    </form>
    <form method="post">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="form-group">
            <h2>Usuarios</h2>
            <li><a href="{% url 'usuario:registrar_usuario' %}">Creacion de usuarios</a></li>
          </div>
        </div>
      </div>
     </form>
      <form method="post">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <div class="form-group">
          <li>
            <a href="{% url 'logout' %}" class="dropdown-toggle" data-toggle="dropdown" role="
            button" aria-expanded="false">LOGOUT<span class="caret"></span>
          </a>
            <a class="btn btn-primary" href="{% url 'logout' %}"></a>
          </li>
        </div>
       </div>
     </div>
    </form>
    {% endblock %}


  </body>
</html>