EmaxCuadrillas/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import login, password_reset, password_reset_done, password_reset_confirm, password_reset_complete, logout_then_login

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^principal/', include('principal.urls'), name='principal'),
    url(r'^casos/', include('casos.urls', namespace='casos')),
    url(r'^cuadrillas/', include('cuadrillas.urls', namespace='cuadrillas')),
    url(r'^usuario/', include('usuario.urls', namespace='usuario')),
    url(r'^accounts/login/', login, {'template_name':'usuario/index.html'}, name='login'),
    url(r'^logout/', logout_then_login,  name='logout'),
    url(r'^reset/password_reset', password_reset, {'template_name':'Registration/password_reset_form.html', 'email_template_name':'Registration/password_reset_email.html'}, name="password_reset"),
    url(r'^reset/password_reset_done', password_reset_done, {'template_name':'Registration/password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>.+)/$', password_reset_confirm, {'template_name':'Registration/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done', password_reset_complete, {'template_name':'Registration/password_reset_complete.html'}, name='password_reset_complete'),
]

casos/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import CasoCreateView, CasoListView, TareaCreateView, TareaListView, TareaUpdateView, TareaDeleteView, CasoUpdateView, CasoDeleteView

# Estas son la urls de casos
urlpatterns = [
    url(r'^eliminartarea/(?P<pk>\d+)/', login_required(TareaDeleteView.as_view()), name='eliminar_tarea'),
    url(r'^editartarea/(?P<pk>\d+)/', login_required(TareaUpdateView.as_view()), name='editar_tarea'),
    url(r'^listatarea', login_required(TareaListView.as_view()), name='tarea_lista'),
    url(r'^tarea', login_required(TareaCreateView.as_view()), name='tarea_nueva'),

    url(r'^eliminarcaso/(?P<pk>\d+)/', login_required(CasoDeleteView.as_view()), name='eliminar_caso'),
    url(r'^editarcaso/(?P<pk>\d+)/', login_required(CasoUpdateView.as_view()), name='editar_caso'),
    url(r'^listacaso', login_required(CasoListView.as_view()), name='caso_lista'),
    url(r'^nuevo', login_required(CasoCreateView.as_view()), name='caso_nuevo')
]

casos/models.py
from django.db import models

class Caso(models.Model):

    TIPOS_PROYECTOS = (
        ('1', 'Mantenimiento'),
        ('2', 'Infraestructura')
    )

    ESTADOS = (
        ('1', 'Ejecutando'),
        ('2', 'Terminado')
    )
    TIPOS_MANTENIMIENTO = (
        ('1', 'Preventivo'),
        ('2', 'Correctivo')
    )

    id = models.AutoField(primary_key=True)
    fecha_inicio = models.DateField(null=False, blank=False)
    fecha_final = models.DateField(null=False, blank=True)
    nombre = models.CharField(max_length=80, null=False, blank=False)
    contacto = models.CharField(max_length=40, null=True)
    telefono_contacto = models.CharField(max_length=8, null=True)
    # Para obtener la cadena de esta campo, se llama al
    # metodo <objeto>.get_tipo_display()
    tipo_mentenimiento = models.CharField(
        max_length=1,
        choices=TIPOS_MANTENIMIENTO,
        default='2'
    )
    tipo = models.CharField(
        max_length=1,
        choices=TIPOS_PROYECTOS,
        default='1'
    )
    descripcion = models.TextField(max_length=200, null=False, blank=True)
    direccion = models.TextField(max_length=200, null=False, blank=True)
    estado = models.CharField(
        max_length=1,
        choices=ESTADOS,
        default='1'
    )
    #Relación uno a muchos, un caso puede tener muchas tareas
    tareas = models.ManyToManyField('Tarea', related_query_name='tareas')

    def __str__(self):
        return self.nombre


class Tarea(models.Model):
    ESTADOS = (
        ('1', 'Ejecutando'),
        ('2', 'Terminado')
    )

    id = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=45, null=False, blank=False)
    duracion = models.IntegerField(null=True)
    estado = models.CharField(
        max_length=1,
        choices=ESTADOS,
        default='1'
    )

    def __str__(self):
        return self.nombre

casos/views.py
from django.shortcuts import render
from django.core.urlresolvers import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
    CreateView
)

from .models import Caso, Tarea


class CasoCreateView(CreateView):
    model = Caso
    fields = [
        'fecha_inicio',
        'fecha_final',
        'nombre',
        'tipo',
        'descripcion',
        'direccion',
        'estado',
        'tareas'
    ]
    template_name = 'casos/caso_form.html'
    success_url = reverse_lazy('casos:caso_lista')

class CasoListView(ListView):
    model = Caso
    template_name = 'casos/caso_list.html'
    context_object_name = 'casos'
    def __str__(self):
        return self.nombre


class CasoUpdateView(UpdateView):
    model = Caso
    fields = [
        'fecha_inicio',
        'fecha_final',
        'nombre',
        'tipo',
        'descripcion',
        'direccion',
        'estado',
        'tareas'
    ]
    template_name = 'casos/caso_form.html'
    success_url = reverse_lazy('casos:caso_lista')

class CasoDeleteView(DeleteView):
    model = Caso
    fields = [
        'fecha_inicio',
        'fecha_final',
        'nombre',
        'tipo',
        'descripcion',
        'direccion',
        'estado',
        'tareas'
    ]
    template_name = 'casos/caso_delete.html'
    success_url = reverse_lazy('casos:caso_lista')

class TareaCreateView(CreateView):
    model = Tarea
    fields = [
        'nombre',
        'duracion',
        'estado',
    ]
    template_name = 'casos/tarea_form.html'
    success_url = reverse_lazy('casos:tarea_lista')

class TareaListView(ListView):
    model = Tarea
    template_name = 'casos/tarea_list.html'
    context_object_name = 'tareas'

    def __str__(self):
        return self.nombre


class TareaUpdateView(UpdateView):
    model = Tarea
    fields = [
        'nombre',
        'duracion',
        'estado',
    ]
    template_name = 'casos/tarea_form.html'
    success_url = reverse_lazy('casos:tarea_lista')

class TareaDeleteView(DeleteView):
    model = Tarea
    fields = [
        'nombre',
        'duracion',
        'estado',
    ]
    template_name = 'casos/tarea_delete.html'
    success_url = reverse_lazy('casos:tarea_lista')

templates/casos/caso_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content %}
    <form method="post">
      {% csrf_token %}
      <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
      <button class="btn btn-danger" type="submit">Sí, Eliminar</button>
      <a class= "btn btn-default" href="{% url 'casos:caso_lista' %}">Cancelar</a>
    </form>
    {% endblock %}
  </body>
</html>

templates/casos/caso_form.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
      Creacion Caso
      {% endblock %}
    </title>
  </head>
  <body>
    {% block content %}
    <form class="" action="" method="post">
      {% csrf_token %}
      <li><h4>Fecha Inicio {{form.fecha_inicio}}</h4></li>
      <li><h4>Fecha Final {{form.fecha_final}}</h4></li>
      <li><h4>Nombre {{form.nombre}}</h4></li>
      <li><h4>Tipo {{form.tipo}}</h4></li>
      <li><h4>Descripcion {{form.descripcion}}</h4></li>
      <li><h4>Direccion {{form.direccion}}</h4></li>
      <li><h4>Estado {{form.estado}}</h4></li>
      {% for form in form.tareas %}
      <form method="get">
        <p><input type="checkbox" name="gender" value="asdf" checked="" >{{form.tarea}}<br></p>
      </form>
      {% endfor %}

      <button type="submit"> Guardar</button>
    </form>
    {% endblock %}
  </body>
</html>

templates/casos/caso_list.html
<!doctype html>
<html>
  <head>
    <meta charset=utf-8>
    <title>
      {% block title %}
      Listado
      {% endblock %}
    </title>
  </head>
  <body>

    {% block content %}
      {% for casos in casos %}
      <tr>
        <li>
          {{casos}}
        <td>
          <a class="btn btn-primary" href="{% url 'casos:editar_caso' casos.id %}">Editar</a>
          <a class="btn btn-primary" href="{% url 'casos:eliminar_caso' casos.id %}">Eliminar</a>
        </td>
      </li>
      </tr>
      {% endfor %}
    {% endblock %}

  </body>
</html>

templates/casos/tarea_delete.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    {% block content %}
    <form method="post">
      {% csrf_token %}
      <h3>¿Desea eliminar el registro de {{ object.nombre }}?</h3>
      <button class="btn btn-danger" type="submit">Sí, Eliminar</button>
      <a class= "btn btn-default" href="{% url 'casos:tarea_lista' %}">Cancelar</a>
    </form>
    {% endblock %}

  </body>
</html>

templates/casos/tarea_form.html
<!doctype html>
<html>
<head>
  <meta charset=utf-8>
  <title>{% block title %}
    CreacionTarea
  {% endblock %}</title>
</head>
<body>
{% block content %}
<form class="" action="" method="post">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit"> Guardar </button>
</form>

{% endblock %}


</body>
</html>

templates/casos/tarea_list.html
{% extends 'principal/principal.html' %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>tarea</title>
  </head>
  <body>
    <form action="">
    {% block content %}
      {% csrf_token %}
      {% for tareas in tareas %}
          <tr>
            <li>
              {{tareas}}
            <td>
              <a class="btn btn-primary" href="{% url 'casos:editar_tarea' tareas.id %}">Editar</a>
              <a class="btn btn-primary" href="{% url 'casos:eliminar_tarea' tareas.id %}">Eliminar</a>
            </td>
          </li>
          </tr>
      {% endfor %}
    {% endblock %}
    </form>
  </body>
</html>